### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by AnimeniacSimey** [matt1tk/SpirtDL#1]
I run .exe file, nothing happens. Please help?

**Comment by matt1tk** [comment]
Make sure you have .net 4.8 installed.

**Comment by AnimeniacSimey** [comment]
I installed, ran .exe file again. Nothing changed.

**Comment by matt1tk** [comment]
Uh, try 4.7.2. :)

**Comment by AnimeniacSimey** [comment]
Details

.NET Framework 4.7.2 or a later update is already installed on this computer.


Won't install :(

**Comment by matt1tk** [comment]
Hm, is there any anti virus installed? Check their logs. It’s currently not
detected as a virus but who knows.

**Comment by AnimeniacSimey** [comment]
Yes, but it didn't detect anything

**Comment by matt1tk** [comment]
PC details? Specifically, CPU? Is it 32 bit or 64 bit?

**Comment by AnimeniacSimey** [comment]
64

**Comment by matt1tk** [comment]
Agh i was afraid of that. Do you happen to have visual studio installed?

**Comment by AnimeniacSimey** [comment]
Yep.

**Comment by matt1tk** [comment]
Did you build it or download the release? If you downloaded the release try
building it on your own PC if you don’t mind.

**Comment by AnimeniacSimey** [comment]
I did, but it says it cant find MyFile.exe and then it says that code is broken or something like that

**Comment by matt1tk** [comment]
Oh, I think I know the issue. Do you have a c:/ drive?

**Comment by AnimeniacSimey** [comment]
Yes

**Comment by matt1tk** [comment]
Hmm. give me a few minutes to work on it, hopefully it’ll fix it.

**Comment by AnimeniacSimey** [comment]
Thanks!

**Comment by matt1tk** [comment]
https://matt1.tk/dl/spirtdl%20testing/Spirthack.exe Try this

**Comment by AnimeniacSimey** [comment]
Do I need to have csgo open? It just deletes itself then nothing happens

**Comment by matt1tk** [comment]
You cannot have csgo open since it kills steam on launch. launch it with
steam not running

**Comment by AnimeniacSimey** [comment]
Nothing happens...

**Comment by matt1tk** [comment]
Ok so that fix did nothing? nothing changed?

**Comment by AnimeniacSimey** [comment]
seems so.

**Comment by AnimeniacSimey** [comment]
Now if I run it, it doesn't delete itself, but nothing happens

**Comment by matt1tk** [comment]
https://matt1.tk/dl/spirtdl%20testing/Spirthack-2.exe Try this

**Comment by matt1tk** [comment]
^this is .net 4.6 which comes preinstalled with win10, so if there's an issue there it should solve it

**Comment by AnimeniacSimey** [comment]
I feel like a broken record XD Nothing happens

**Comment by matt1tk** [comment]
Alright, I'm not sure what to say man. I'm working on a workaround for you rn

**Comment by AnimeniacSimey** [comment]
Thanks man... really appreciate it!!!

**Comment by matt1tk** [comment]
Alright here you go. https://github.com/matt1tk/SpirtDL2 run the bat called spirtdl to download and run loader. then opencsgo.bat. put both on your desktop

**Comment by matt1tk** [comment]
Does https://github.com/matt1tk/SpirtDL2 fix your issue?

**Comment by AnimeniacSimey** [comment]
Where in my C: Drive does it go?

**Comment by AnimeniacSimey** [comment]
Like program files or

**Comment by AnimeniacSimey** [comment]
Also, it says SpirtDL2 
ERROR: The process "steam.exe" not found.
ERROR: The process "csgo.exe" not found.

**Comment by matt1tk** [comment]
Anywhere, desktop is most convenient. And that error is fine, it just
closes steam and csgo if it’s running, if it’s not, it’s not an issue.

**Comment by AnimeniacSimey** [comment]
? No like... the spirtdl.bat is on my desktop, steam isn't open. Nothing. I open the bat, it says the errors, then it closes. Nothing else. So what do I do?

**Comment by AnimeniacSimey** [comment]
Also, i get this (sorry about my desktop, I couldn't screenshot fast enough)
![bruh](https://user-images.githubusercontent.com/51385180/69831850-57747400-11f9-11ea-8cd3-ff6cec153f63.PNG)

**Comment by matt1tk** [comment]
It’s got to be an issue with your antivirus. The bat file is the lowest
level possible, it just downloads the exe and runs it.

**Comment by matt1tk** [comment]
Did you try running the bat as admin?

**Comment by AnimeniacSimey** [comment]
Works! um... do I need a spirithack account for this? I thought it was a crack

**Comment by matt1tk** [comment]
You still need an active sub... it downloads the loader. that’s all it does

**Comment by AnimeniacSimey** [comment]
Ahh.. I see XD But tysm for being so patient with me bro I really appreciate it
